# Generated by Django 5.2.2 on 2025-06-07 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
            ],
            options={
                'verbose_name': 'Catégorie de document',
                'verbose_name_plural': 'Catégories de documents',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('form_definition', models.JSONField(default=dict, help_text='Définition JSON du formulaire pour ce modèle.')),
                ('template_file_path', models.CharField(blank=True, help_text="Chemin vers le fichier modèle (ex: 'docx_templates/contrat_bail.docx')", max_length=500, null=True)),
                ('ohada_compliance_details', models.TextField(blank=True, help_text='Détails sur la conformité OHADA.', null=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Indique si ce modèle est activement proposé aux utilisateurs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates', to='api.documentcategory')),
            ],
            options={
                'verbose_name': 'Modèle de document',
                'verbose_name_plural': 'Modèles de documents',
                'ordering': ['name', '-version'],
                'unique_together': {('name', 'version')},
            },
        ),
    ]
