# Generated by Django 5.2.2 on 2025-06-07 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.JSONField(help_text="Données fournies par l'utilisateur pour générer ce document.")),
                ('file_path', models.CharField(blank=True, help_text='Chemin vers le fichier de document généré.', max_length=1024, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente de génération'), ('generating', 'Génération en cours'), ('completed', 'Terminé'), ('failed', 'Échec de la génération'), ('archived', 'Archivé')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('template_version_at_generation', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='generated_instances', to='api.documenttemplate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document Généré',
                'verbose_name_plural': 'Documents Générés',
                'ordering': ['-created_at'],
            },
        ),
    ]
